
image:
- Visual Studio 2017
- Visual Studio 2017 Preview

environment:
  matrix:
    - platform: x86
      generator: Visual Studio 15 2017

    - platform: x64
      generator: Visual Studio 15 2017 Win64

install:
- mkdir build
- cd build
- cmake -G "%generator%" ..

build_script:
- cmake --build . --target test_nanorange --config Debug

test_script:
- ctest -C Debug
