
image:
- Visual Studio 2017
- Visual Studio 2017 Preview

install:
- mkdir build
- cd build
- cmake ..

build_script:
- cmake --build . --target test_nanorange --config Debug

test_script:
- ctest -C Debug
